# Generated by Django 4.1 on 2024-06-19 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='cpf')),
                ('nome_cli', models.CharField(max_length=200, null=True, verbose_name='nome')),
                ('endereco_cli', models.CharField(max_length=200, null=True, verbose_name='endereco')),
                ('cidade_cli', models.CharField(max_length=200, null=True, verbose_name='cidade')),
                ('estado_cli', models.CharField(max_length=2, null=True, verbose_name='estado silga')),
                ('cep_cli', models.CharField(max_length=10, null=True, verbose_name='cep')),
                ('Email_cli', models.CharField(max_length=200, null=True, verbose_name='email')),
                ('telefone1_cli', models.CharField(max_length=11, null=True, verbose_name='telefone')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='ItemPed',
            fields=[
                ('coditem_ite', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('Código_da_empresa', models.IntegerField(null=True, verbose_name='codigo da empresa')),
                ('Código_do_produto', models.IntegerField(null=True, verbose_name='codigo do produto')),
                ('Quantidade', models.IntegerField(null=True, verbose_name='quantidade')),
                ('Preço', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='valor do produto')),
            ],
            options={
                'verbose_name': 'item pedido',
                'verbose_name_plural': 'itens pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codped_ped', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='cnpj')),
                ('hora_ped', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e hora ')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
    ]
