# Generated by Django 5.0.3 on 2024-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPed',
            fields=[
                ('coditem_ite', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('Código_da_empresa', models.IntegerField(null=True, verbose_name='codigo da empresa')),
                ('Código_do_produto', models.IntegerField(null=True, verbose_name='codigo do produto')),
                ('Preço', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='valor do produto')),
            ],
            options={
                'verbose_name': 'item pedido',
                'verbose_name_plural': 'itens pedidos',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('codped_ped', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='cnpj')),
                ('hora_ped', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data e hora ')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
            },
        ),
    ]
