# Generated by Django 4.1 on 2024-04-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemped',
            name='Quantidade',
            field=models.IntegerField(null=True, verbose_name='quantidade'),
        ),
    ]
