# Generated by Django 4.1 on 2024-06-19 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bairro_cli',
            field=models.CharField(max_length=200, null=True, verbose_name='bairro'),
        ),
    ]
