# Generated by Django 4.2.10 on 2024-03-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contactar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Codigo')),
                ('nome', models.CharField(blank=True, max_length=20, null=True, verbose_name='name')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='email')),
                ('mensagem', models.CharField(blank=True, max_length=3000, null=True, verbose_name='texto')),
            ],
            options={
                'verbose_name': 'contactar',
                'verbose_name_plural': 'Contactares',
            },
        ),
    ]
